name: GitHub-Profile-3D-Contrib

on:
  schedule: # 10:35 CST == 2:35 UTC
    - cron: "35 2 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{secrets.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}}
          USERNAME: ${{github.ori1999}}
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "generated"
          git push
